### ISSUE TITLE
Change to plug ins Supported Contexts

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#10]
Should be possible to turn off the extra fields per context.

A multiselect drop-down with the supported (tested) contexts?

If needed, a text field where other contexts can be added and merge them with the above selected.? 

Makes the "publishing" easy and understandable. If I now, as is, remove user and module it's hard to remember what to add to activate it later.

A simple info text could also do.  "Default supported contexts: com_content=article,category,form, com_users=user,profile, com_module=module"

Extra fields for categories should be controlled by com_mycomponent and not by com_content.
It's now enabled for all categories.

-- Sorry, I now saw that it's added to the left menu but with a link to dpfields->com_content.article. So this is a bug.

**Comment by laoneo** [comment]
Can you post a screenshot where exactly it is added?

**Comment by laoneo** [comment]
This is already possible trough the system plugin. When it will be part of Joomla core, then every core component can be configured to use custom fields.
