### ISSUE TITLE
Bug - Extra fields for categories

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#11]
I think there are general problems with the categories and Extra fields.

e.g. The extra fields for categories are taken from articles. I added a value to an article. I got the same field and value for a category with the same id. Changed tha value and got his changed value in the article.

**Comment by laoneo** [comment]
You need to provide more information how to reproduce the issue.

**Comment by schnuti** [comment]
I thought it was understandable.
1. Create an extra field for articles.
2. Look up one article and one article-category with the same id. Hard to find on a live site but on a test you should be fine.
3. Edit the article by adding a value to the extra field.
4. Edit the category with the same id as the article.
5 You'll see the value from the article.

**Comment by schnuti** [comment]
As I wrote in the other issue this is another bug.

Open a category view for another component.
index.php?option=com_categories&view=categories&extension=com_mycomponent

You'll se a "Fields" at the top of the left menu
This is linked to:
?option=com_dpfields&context=com_content.article

**Comment by schnuti** [comment]
You can close this. Also tests for  "outside use" pf DPFields
