### ISSUE TITLE
More comments

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#14]
1. I've found the first problem with categories
What's this? onAfterRoute () in plugin

		if ($component == 'com_dpfields' || $component == 'com_categories')
		{
			$context = $app->input->getCmd('context', 'com_content');

2  I do think that more settings are needed to get it to work properly. The plugin needs more data that can not be retrieved by the hml-query and the plugin parameters used now. 
+ component (+ section) (+ category) 
+ backend views where to add the dpfields menu
+ context to add to the dpfields table
+ backend views where to add the dpfields tab
+ what context to use in those views
+ frontend views where to inject extra fields
+ what context to use in those views

Those can be repeated.

My suggestion is:
- Only keep the supported/activated components ( + categories ) as normal parameters.
- Introduce a xml file per component where the details are added. XML files are used by Joomla and other extensions in a lot of cases.
Oh -- remember the good old days with Joom!Fish ;) That extension did almost the same thing, not adding but replacing/translating fields in the views. Today is the same technique used by e.g. redCore's translation component.

-> means for the plug in
first --> check if the called option = component is supported, In the case of category check component (+ section) + category
second --> if yes try to load the xml file for the rest.

3. I'm not convinced that the extra fields are needed for modules. The Joomla modules are very flexible and if you really need something more, it's that easy to fork.
If you know how to use Extra fields in components you should be able to fork a module in minutes.

**Comment by laoneo** [comment]
When DPFields will be added to the core, then this checks will be obsolete anyway, as DPFields can be integrated then correctly into the core components, without introducing a new xml file.

Modules are a request from other users, and it makes absolutely sense to add custom fields to them as well.

**Comment by schnuti** [comment]
You didn't answer #1.

Are you talking about core components? I'm not! 
I'm only interested, if it's about supporting components in general. Then you have more then one view / table and more then one category section per component.
You have to have more settings, I'm sure you can't hardcode it and hope it works.

There are alternatives for com_content and extra fields are covered by the user profile plugin that is easy to adopt.

Can you please give me an example how you benefit from extra fields in modules?

**Comment by laoneo** [comment]
If you don't want extra fields in modules, that exclude it in the DPFields system plugin, and you are good to go.

**Comment by laoneo** [comment]
At the bottom of that page https://joomla.digital-peak.com/documentation/162-dpfields/2756-developer you can see how to add multiple contextes for one component. For example on the DPCalendar event component you can add fields for locations, attendees and events. In version 1.1 I will add the possibility to categorize the fields. Every category will be then it's own tab in the edit form.

**Comment by schnuti** [comment]
Maybe I missunderstood you.
You don't aim to get it to work with "any" third party component? It has to be integrated witihin the component? I've tried to understand how it, like now with articles and article categories, could work. It does not work properly.

To handle "any" third party component, that fulfills basic requiements, is maybe to hard.

**Comment by laoneo** [comment]
Working with any third party component out of the box is definitely too hard, that's why com_categories must be linked by code within the component. If you know that a component will work with DPFields, then  you can add it in the system plugin.

> It does not work properly.

What does not work properly with articles?

The aim of DPFields is to allow the component developer to link easily his component to DPFields with a few conventions and code modifications. To work out of the box with any component can perhaps be done within Joomla 4 or 5 when the Entities concept will be implemented, but not now as it is actually a battlefield the component development in Joomla.

**Comment by schnuti** [comment]
Not working:
 Can't test right now, but as I remember, the default setting is to show fields for categories. Then the Fields menu item (for article) appears everywhere.
As you say, integrating it into the components will remove that.

i.e. to realy test it, I have to modify the com_content menus or use my own component..

**Comment by laoneo** [comment]
Ok. Then I will close that issue.
