### ISSUE TITLE
JLayout for single fields

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#15]
Another approach for JLayouts
Let's say the extra load because of JLayout is not that important ,could this be a way? Most use cases will not have that many extra fields. 

When you have groups (categories), each group can create a container using JLayout and within that a JLayout for each field. I presume that those fields also are grouped according to the wanted output.

The JLayout for the group (container) and for the fields has to be choosen in the group  and field manager.

Now there has to be some predefined layouts with different html tags. 
For groups  e.g. 
dl ( default?), div, ul, ol
For fields e.g.
dd (default?), div, li, image
.................

Another setting for the group:
Show in conten event

- onContentBeforeDisplay
- onContentAfterDisplay
- onContentAfterTitle
- none

**Comment by schnuti** [comment]
I think the code would be similar to my PR.

**Comment by laoneo** [comment]
Automatically generating layout files with PHP code would be too advanced.
