### ISSUE TITLE
A minor problem with your Hello World test

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#16]
A php notice because some content plugins need a field $text.
I solved it quick and dirty in the frontend  model line 76.

   $query->select('h.id, h.greeting, h.params, c.title as category, h.greeting as text' )

I guess testers turn on error messages.

**Comment by schnuti** [comment]
2 problems - 2 PR's ( 1 + 2 ) in your Hello World
The fix above and more important because it breaks the HW backend.

JFolder has to be loaded

**Comment by laoneo** [comment]
Merged and commented, thanks.
