### ISSUE TITLE
JFiles missing in files view

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#17]
With plugin disabld JFiles is not loaded.

Should the fields creation run without activated plugin. I guess yes.
Then add: 

JLoader::import('joomla.filesystem.file');

If not, there has to be a check, if the plugin is enabled somewhere early e.g. the controller.

JPluginHelper::isEnabled(''system', 'dpfields') ---> Please activate the plugin!

I'll add the first as PR to GitHub

**Comment by schnuti** [comment]
PR #19

**Comment by laoneo** [comment]
Merged
