### ISSUE TITLE
Tests with Hello World

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#20]
There are some problems with Hello World. Probably because it's not up to date with Joomla.
The submenus (sidebar) are "funny". It might be, that the sidebar HAVE to be used and not the old submenu.

The item edit has no tabs. Is only styling, but you have to scroll down to the bottom to find the extra fields.

I'll try to edit the code, but I'm not sure, I can edit it on GitHub without messing things up. 

The frontend view is now ok.

**Comment by laoneo** [comment]
I made it with as less changes as possible to the original branches. It would then not confuse the new developers.
