### ISSUE TITLE
Tested some addiional functionality

### ISSUE THREAD

**Issue by schnuti** [Digital-Peak/DPFields#21]
I've added what I find missing.

- To group the fields I added Joomla categories to the DPFields component. 
For each group a new tab is created - hopefully not too many.
Very complex for the issue but no need for additional code and table. ACL could be used.
One problem is, that I didn't find a way to return to the original compnent. 

- Added 3 fields to those categories. 
(Easy to add. Only need a category.xml and the new fields are added to params).
  1. Container eg DIV, 
  2. class for the container, 
  3. show group: Before content, After title, After content, Do not show -> use override.

- Output controlled by those groups.

- Added a choise to select individual JLayout file per field. Compare selection of tmpl overrides for components and modules. There can only be some predefined ones. The variations are almost endless, so the user should know how to create new ones or override existing.

This concept works for me.
.

**Comment by schnuti** [comment]
Tis reminds me, that the most simple way for com_conent to add extra fields, would be to add the same functionality as com_categories. The user then only has to add an xml file and override the frontend article views or wrie a plugin for it. Or what ever.

**Comment by laoneo** [comment]
You did that without DPFields?
