### ISSUE TITLE
Data not captured

### ISSUE THREAD

**Issue by renekreijveld** [Digital-Peak/DPFields#22]
I have a server running PHP 5.5.19 and DPFields 1.0.7. I have added a few fields. When I edit an article and add data in the extra fields and save the article the extra fields data is not saved.
In the plugin code dpfields.php I added a line withg print_r($params);die();
This gives me empty output. Any idea what could be the problem here?
Server is running PHP 5.5.19, MySQL 5.6.22.

**Comment by renekreijveld** [comment]
I managed to debug soem more. In the dpfields.php plugin code line 140
$data = JFactory::getApplication()->input->post->get('jform', array(), 'array');
The data is empty.

**Comment by renekreijveld** [comment]
Problem solved. After updating the server to PHP 5.5.30 this issue is resolved.

**Comment by AndyGaskell** [comment]
I seem to have the same / similar issue with PHP 5.5.9.
just adding this note for future googlers.
