### ISSUE TITLE
Chinese Characters not displayed correctly

### ISSUE THREAD

**Issue by xiaowo** [Digital-Peak/DPFields#23]
I am using the DPFields plugin in an DP Calender Event with a Field with type "Text" . If i write chinese characters into the field, the characters are not displayed correctly on the homepage. I am using DPFields V1.0.6. Please check this behaviour also by yourself, if it is really a bug ( even i don't think it is a problem just at my homepage) and please fix it in the next version.   Probably this is just a problem of the DPCalender component, but i don't think so, since in an DPCalender Event i can write chinese characters without any problems in any other regular fields.
My joomla version is 3.4.4, DPCalender Version 5.2.4
Would be very nice if this problem can be fixed, since i use this for my friends charity homepage, who is helping chinese kids.
Thank you very much.

**Comment by laoneo** [comment]
Can you post a screenshot where do you add the Chinese characters?

**Comment by xiaowo** [comment]
Ok
First screenshot is the input field in the event:
![screenshot_fields_bug1](https://cloud.githubusercontent.com/assets/7569721/11449787/55b4b9ec-95be-11e5-8f6d-43d4ca0b9cf5.PNG)

Second one is the screenshot on the homepage:

![screenshot_fields_bug2](https://cloud.githubusercontent.com/assets/7569721/11449776/dc42a7cc-95bd-11e5-91e6-3c52581ce796.PNG)

**Comment by laoneo** [comment]
Can you share a link to your site that we can have a look. I'm interested to see if the characters are wrong encoded.

**Comment by xiaowo** [comment]
http://www.loveppi.com/index.php/en/component/dpcalendar/event/9

**Comment by laoneo** [comment]
I tested it with protostar on a Joomla 3.4.5 installation and it worked. Can you try it with protostar? Can you post here the chinese characters you have inserted?

**Comment by xiaowo** [comment]
i also checked it now on my local joomla installation and it also works there. So it seems its really a problem of the installation on our webserver :p.  Thanks for your effort  :)
