### ISSUE TITLE
Fields Tab missing

### ISSUE THREAD

**Issue by pknad505** [Digital-Peak/DPFields#24]
The fields tab on the new article or editing an article has disappeared and I cannot work out how to bring it back. I am using the most upto date version of DPFields (1.0.7) and it is enabled in the plugins menu. I have successfully entered articles with data in the fields tab in the past and on the front end of the page they are rendering however now I am unable to get to the field tab of these articles to appear.

**Comment by pknad505** [comment]
I have uninstalled and reinstalled DPFields.All fields have on both front and back end have gone.
So I have then added a new field to all categories but that doesnt show in the article editor still.
DPcalender is also installed.

**Comment by laoneo** [comment]
Did you do some article form layout overrides? Do you see the fields on the back end?

**Comment by laoneo** [comment]
Did you set error reporting to maximum in your Joomla configuration? Is there an error shown?

**Comment by piotr-cz** [comment]
Make sure you have an option
_Configure Edit Screen > Show Article Options_ should be set to _Yes_.

Either in Content options or in Article edit screen.
