### ISSUE TITLE
If Fields is empty problem

### ISSUE THREAD

**Issue by RYAN-JIM** [Digital-Peak/DPFields#27]
dear leader:
i have a questiom about fields if emply
frist, i had change the css file of template and add the class 'dpfields-container' with border
something old articles without fields and fields is empty for cliend, but the css class 'dpfields-container' with border is also appear in the all articles with empty fields
how can i to fix it?
thank you, sir

**Comment by laoneo** [comment]
Sorry but I don't understand your question? What exactly is not working?

**Comment by RYAN-JIM** [comment]
​
the first article i' d add fields type
the second and other more articles without fields type, but the border css
styer is still here.

i'd search from the source code and find the code like'<dl
class="dpfields-container
article-info muted"></dl>' will appear in the all pages.



i want to know how to fix when fields is empty and border will not appear
 thank you, leader​


2016-02-01 15:17 GMT+08:00 Allon Moritz <notifications@github.com>:

**Comment by laoneo** [comment]
As you can see here https://github.com/Digital-Peak/DPFields/blob/master/com_dpfields/site/layouts/fields/render.php#L45. It doesn't create any output at all when there are no fields.

**Comment by RYAN-JIM** [comment]
but, it will create code like # <dl class="dpfields-container article-info muted"></dl> at all when there are no fields, the styer will output when i add .dpfields-container {border: 1px dashed #2b95e6;} into template.

**Comment by laoneo** [comment]
No It will not. I tested it several times. Make sure you have the latest version installed. If you want that we should debug the issue on your server, then you need to have an active subscription at https://joomla.digital-peak.com which comes with support for DPFields.
