### ISSUE TITLE
Error on tags view

### ISSUE THREAD

**Issue by marcodings** [Digital-Peak/DPFields#3]
In my setup with fields assigned to articles, any display of articles based on tags produces the following error:
Fatal error: Call to a member function get() on a non-object in /plugins/system/dpfields/dpfields.php on line 505
When the dpfields system plugin is disabled all tag related content works as expected.

kr Marco

**Comment by laoneo** [comment]
In my opinion this is a bug in Joomla tags view as the params parameter is passed as string.
