### ISSUE TITLE
rendering DPFields inside a module override

### ISSUE THREAD

**Issue by allrude** [Digital-Peak/DPFields#34]
Hi Allon, 
can you please explain how I can render field(s) inside a module override ( mod_arcticle_category for example) rendering it as in an Article or Category override doesn't do the trick.

Reagards

Ruud van Zuidam

**Comment by fastnetwebdesign** [comment]
I'd be very interested in this also - I tried a few things last night with no joy :(

**Comment by laoneo** [comment]
Basically you have to prepare it like in the article view here https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/view.html.php#L161. Then you have a dpfields array attached to the item which you can loop over.

**Comment by mark-work** [comment]
Hi Allon,

Please can you explain in more detail?  I'm trying to render a field in a [Flexi Custom Code](http://extensions.joomla.org/extension/flexi-custom-code) module override.  Perhaps the documentation could have examples of rendering fields in modules?

Many thanks

Mark

**Comment by laoneo** [comment]
The problem is that you need to get an article first to render the field in a module. @allrude has already the articles, but your custom one not.

**Comment by mark-work** [comment]
Thanks for you're quick response.

What would be the solution?  Would I need to switch to a different module type - mod_custom instead, for example?  Sorry, I don't quite understand why the DPField can't be read as module configuration parameters would be.  If you can please let me know what I need to do to get this working that would be great.  I'm not an expert on Joomla modules.

(F.Y.I - I tried posting this question on the [support page](https://joomla.digital-peak.com/support) but the page is broken)

**Comment by laoneo** [comment]
This issue tracker is for bug reports only. Please ask your support question on our support platform at https://joomla.digital-peak.com/support, that's where you will get the best and fastest help. You need to have an active subscription to get support for our Joomla extensions. If you don't have one you can get it from [here](http://joomla.digital-peak.com/subscribe). 

Subscriptions allows us to develop our open source extensions, it allows us to pay the server costs and to participate in the [active development](https://github.com/joomla/joomla-cms/pulls?q=is%3Apr+author%3Alaoneo+is%3Aclosed) of the Joomla CMS. It is YOUR contribution to the open source community. Thank's for understanding.
