### ISSUE TITLE
Fatal error - Filed categories 

### ISSUE THREAD

**Issue by ch2856** [Digital-Peak/DPFields#36]
j3.5.1 on xammp with php 7.x. when I click on Files Categories I get: 
Fatal error : Cannot use 'String' as class name as it is reserved in C:\xampp\htdocs\joom\libraries\vendor\joomla\string\src\String.php on line 19

**Comment by laoneo** [comment]
This is a bug in Joomla 3.5.1 which is fixed for the next version 3.6.0 https://github.com/joomla/joomla-cms/pull/9704. You need to replace the file libraries/vendor/joomla/string/src/Inflector.php with the file here https://github.com/joomla/joomla-cms/blob/74fb06f6447b5f6912fa1090e96affbeb3e35b98/libraries/vendor/joomla/string/src/Inflector.php. Then it should start working. I guess it has to do with caching.

**Comment by ch2856** [comment]
Thanks, working now. One small comment, I would change the H1 from "Categories" to "Fields Categroies" - it confused me for a second.

**Comment by laoneo** [comment]
I'm going to rename it to Field Groups.
