### ISSUE TITLE
A way of getting values programmatically.

### ISSUE THREAD

**Issue by AndyGaskell** [Digital-Peak/DPFields#38]
This is not so much an issues as a question or perhaps feature request.
I was wondering if there was a way of getting values programmatically?

So, as a bit of background, I'm just wanting to pull a field value and display it in a template override.  There is a bit more background on my question at http://joomla.stackexchange.com/questions/16570/dpfields-display-values-in-module

Previously I've used FieldsAttatch quite a lot, and there is a nice helper / API solution in that extension which is documented at http://www.fieldsattach.com/index.php/support/api-for-template

So really perhaps just a function with two parameters, one for article id or object and one field id or name.  This would return the rendered value.  So, like one of the following...
```
$field_value = DPFieldsHelper::getValue($article_id, $field_id);
$field_value = DPFieldsHelper::getValue($article_id, $field_name);
$field_value = DPFieldsHelper::getValue($article_object, $field_id);
$field_value = DPFieldsHelper::getValue($article_object, $field_name);
```

So, I'm wondering...
1) Is there a way to do this, or something similar, in DP Fields?
2) If not, I could write some code and do a Pull request, would that be useful?

The closest thing I could find was...
```
JLoader::register('DPFieldsHelper', JPATH_ADMINISTRATOR . '/components/com_dpfields/helpers/dpfields.php');
$fields = DPFieldsHelper::getFields("com_content.article", $article, TRUE);
```
...which is workable, it returns an object with the value as one element, but it'd be neater and quicker if you could just the value on it's own.

Also, just to say, thank you for writing this great extension, it's a really nice, clean and elegant solution to adding fields to Joomla.

**Comment by laoneo** [comment]
Answered on stackexchange. Hope you will accept then my answer :-)

**Comment by AndyGaskell** [comment]
Thanks Laoneo, that sounds good and makes sense.
