### ISSUE TITLE
If the item parameter is passed into DPFieldsHelper->getFields method as an array the language is not set correctly

### ISSUE THREAD

**Issue by williamsandy** [Digital-Peak/DPFields#40]
I have noticed that if the item parameter is passed in as an array that the following line does not get set by the item language value
 line 104: 

` self::$fieldsCache->setState('filter.language', array('*', isset($item->language) ? $item->language : JFactory::getLanguage()->getTag())); `

This is because the explicit cast of the item parameter to an object is done after this on line 109:
```
if (is_array($item))
        {
            $item = (object) $item;
        }

```

so in short filter.language is alsways set to the language defined by Joomla and not by the item/article if item is passed in as an array.

This is the same for com_fields also. Is this done by design?

**Comment by laoneo** [comment]
Where can I find that code snippet?

**Comment by williamsandy** [comment]
DPFieldsHelper->getFields method from line 104  similar with  FieldsHelper->getFields  in com_fields component


`public static function getFields ($context, $item = null, $prepareValue = false)
	{
		if (self::$fieldsCache === null)
		{
			// Load the model
			JLoader::import('joomla.application.component.model');
			JModelLegacy::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_dpfields/models', 'DPFieldsModel');
			self::$fieldsCache = JModelLegacy::getInstance('Fields', 'DPFieldsModel', array(
					'ignore_request' => true
			));
			self::$fieldsCache->setState('filter.published', 1);
			self::$fieldsCache->setState('filter.language', isset($item->language) ? $item->language : JFactory::getLanguage()->getTag());
			self::$fieldsCache->setState('list.limit', 0);
		}
		self::$fieldsCache->setState('filter.context', $context);

		if (is_array($item))
		{
			$item = (object) $item;
		}......`

**Comment by laoneo** [comment]
How can I reproduce the issue. For me the code looks right.

**Comment by williamsandy** [comment]
if $item is passed into the getfields function as an array how will 

isset($item->language)  on line 104  ever evaluate to true?

You are doing the explicit cast of the $item parameter to an object on line 109. That is too late for the above code on line 104 as $item as it is not an object at that point but an array.
