### ISSUE TITLE
How can show the extra field (DPFields) in category blog view / category list view in Joomla?

### ISSUE THREAD

**Issue by wilsontse88** [Digital-Peak/DPFields#41]
How can show the extra field  (DPFields) in category blog view / category list view in Joomla?

I added the extra new field in article. However, category list view still cannot show in menu - category view.

how could I do?

Thanks

**Comment by laoneo** [comment]
This issue tracker is for bug reports only. Please ask your support question on our support platform at https://joomla.digital-peak.com/support, that's where you will get the best and fastest help. You need to have an active subscription to get support for our Joomla extensions. If you don't have one you can get it from [here](http://joomla.digital-peak.com/subscribe). 

Subscriptions allows us to develop our open source extensions, it allows us to pay the server costs and to participate in the [active development](https://github.com/joomla/joomla-cms/pulls?q=is%3Apr+author%3Alaoneo+is%3Aclosed) of the Joomla CMS. It is YOUR contribution to the open source community. Thank's for understanding.

**Comment by wilsontse88** [comment]
Where can post my question the on "https://joomla.digital-peak.com/support" page? Because I am newbie on Dpfield and I  just registered be your member and I have not find the post area.

could you tell me the location of the post comment area on the support page?

thanks.
