### ISSUE TITLE
DPFields interferes with per-user editor settings

### ISSUE THREAD

**Issue by njbair** [Digital-Peak/DPFields#43]
So I discovered this weird bug and was able to isolate DPFields as the cause. It basically causes a user's Editor setting to be applied globally. Full bug report below.
### Expected Behavior

Each user sets his preferred editor under _User Menu > Edit Account > Basic Settings_.
### Actual Behavior

Whenever one user changes his preferred editor, the setting is applied to all users.
### Steps to Reproduce
1. Install Joomla.
2. Create multiple user accounts with administration privilege.
3. Install DPFields.
4. Under _User Menu > Edit Account > Basic Settings_, modify the _Editor_ setting for any single user.
5. Check other user accounts and observe the setting applied to all of them.
6. Repeat steps 4 & 5 with other user accounts to confirm.

**Comment by laoneo** [comment]
Thanks for reporting, I will have soon a look.

**Comment by njbair** [comment]
Thanks. Not sure if it's related, but we've also been having some site-wide permissions issues, in case that helps you in your diagnosis.

**Comment by thomasdebay** [comment]
Hello, I'm not sure if it's related either, but here is another problem with permissions I have noticed.
- Set up different user groups and a category for each one of them.
- Allow each user group to publish into one category and one category only.
- The default Joomla behavior when one of these users created an article is to auto-select the category they're allowed to publish in.
- As soon as I enable DPFields, my users are unable to select any category at all.

Actually, there's another problem:
- With DPFields disabled, add a menu link to create a new article in a category. Select a default category assigned to one specific user group.
- Try to create an article with this link while logged in as a user who doesn't have the permissions to publish in the default category you selected.
- Joomla shouldn't let you create the article in this category. Instead, it automatically selects the only category your user is allowed to write in.
- With DPFields enabled, any user can create an article in any category, as soon as they use a menu link that pre-sets a default category.

I hope this helps. Please let me know, should you need additional information.

**Comment by laoneo** [comment]
I'm closing this one as custom fields was shipped with Joomla 3.7 and DPFields doesn't have the custom fields functionality anymore. Instead of it is now a CCK!
