### ISSUE TITLE
Image Field appears in the Frontend also, if None image selected

### ISSUE THREAD

**Issue by ufuk-avcu** [Digital-Peak/DPFields#47]
System: Joomla 3.6.4, Protostar, DpFields Core 1.3.2

1. Create a Image Field.
2. Go to your article.
3. In the image field don't select an image.
4. Go in the Frontend to your article.

Expected result: No DpFields related output, because no image was selectet.
Actual result: You can see a Image Field Label and a Placeholder for a broken Image.

Screenshot:
![capture1](https://cloud.githubusercontent.com/assets/13818234/21048226/7229fd52-be0e-11e6-9e43-cff75d089b10.png)

**Comment by laoneo** [comment]
Fix will be shipped with next release.
