### ISSUE TITLE
DPField 'yesno' ignores 'no' value

### ISSUE THREAD

**Issue by degobbis** [Digital-Peak/DPFields#50]
If a 'yesno' field is used, 'no' is overwritten as a value if the default value is set to 1.
This does not make it possible to set an initial value for 'yes', and then set it to 'no'.

**Comment by laoneo** [comment]
I'm closing this one as custom fields was shipped with Joomla 3.7 and DPFields doesn't have the custom fields functionality anymore. Instead of it is now a CCK!
