### ISSUE TITLE
Categorize Fields

### ISSUE THREAD

**Issue by laoneo** [Digital-Peak/DPFields#6]
Fields should be categorized and these categories should be displayed as tabs in the form.

**Comment by schnuti** [comment]
Good idea!
What kind of category? Joomla is a little heavy and where would you add the categories? As is, the article categories are shown in the drop down. 

Wouldn't it be enough to allow the user to enter a number for each field as a grouping number. The grouping is per extension.

With Joomla categories you could check the ACL for the tabs.

**Comment by laoneo** [comment]
A new menu link like "Fields Categories" will be added to the sidebar then.
