### ISSUE TITLE
Layout for fields

### ISSUE THREAD

**Issue by laoneo** [Digital-Peak/DPFields#7]
Fields should be rendered trough their own layout instead of a generic one.

**Comment by schnuti** [comment]
This issue may be the same as mine.
You need some kind of field identity to be able to override single fields.
e.g. simply add icons to user profile fields, telephone, home, .......

- Add the field id to the JLayoutHelper::render('field.render', array ?
- Use of 1 layout per field? e.g. field.render1, field.render2 .. default field.render. Where the number is the field numbers (1,2 ...) ?

**Comment by laoneo** [comment]
This is not the same, as the output of the field itself which prepares the value to display is actually in it's own class. This should be extracted into JLayouts. I'm talking about this code https://github.com/Digital-Peak/DPFields/blob/master/com_dpfields/admin/models/types/base.php#L72.
