### ISSUE TITLE
Uninstalling causes fatal error, unable to access Joomla administrator

### ISSUE THREAD

**Issue by rhellyer** [Digital-Peak/DPFields#8]
I uninstalled DP Fields and received this error:

Fatal error: Class 'DPFieldsHelper' not found in /home/[redacted]/plugins/system/dpfields/dpfields.php on line 701

Subsequently I was unable to get access to my administrator control panel because it came up with the same error each time.

I was able to correct this by manually deleting the dpfields plugin entry from the #__extensions table

**Comment by laoneo** [comment]
This is fixed in 02998ee1c8170b02c1facc8fa52dac963101a2d7. Will be shipped soon with 1.0.7.
