### ISSUE TITLE
Overwrites behavior of Category dropdown menu 

### ISSUE THREAD

**Issue by rhellyer** [Digital-Peak/DPFields#9]
It appears that DP Fields overrides the behavior of the Category choice dropdown menu on all extensions. I presume that it does this so that it can insert the correct fields tab in the event that a user changes the category setting.

However this behavior persists in other extensions which use the category dropdown in admin. Ironically I noticed this when using FieldsAttach since the DPfields caused the input form of fields attache to refresh each time a category was chosen! :)

**Comment by laoneo** [comment]
Can you post a screenshot where the field is overridden?

**Comment by schnuti** [comment]
I can't confirm this. Tested a couple of components. The category drop down list is correct in item edit. Or does he mean the same as what I wrote about the left side menu? Fields appears for all components/categories. 

over

**Comment by rhellyer** [comment]
Here's what I did
1. installed dp fields
2. created a field and associated it with a specfic category ('film', say)
3. created a test article, saved it
4. changed the test article's category to 'film' and noted that the page was redirected and the new 'fields' tab appeared as one would expect.
---- at this point so far so good
5. went to a different component that I had installed (fieldsattach)
6. in this components configuration menu there is an option for choosing a category. 
7. now when I chose that category (see screenshot) the page is still redirected, but any data that I had entered is lost on that page (because the component, I presume is not expecting to be redirected in this fashion)

I would guess that dpfields has added an event behavior so that when a user chooses a different category for an item the page is redirected so that any fields associated with that category can be inserted on the form. However, some components presumably use the category chooser simply to select a category, and do not anticipate that their page will be redirected. I haven't had time to see if this is the case in other components than fieldsattach that use a category chooser field.

I am traveling for this coming week, but hope that this is enough to help (screenshots attached)

Richard
![dpf2](https://cloud.githubusercontent.com/assets/3446553/10436922/8aea284a-70de-11e5-9a19-d1e21aecf4f0.png)
![dpf3](https://cloud.githubusercontent.com/assets/3446553/10436923/8af08780-70de-11e5-8478-4242619c8f84.png)

**Comment by schnuti** [comment]
Richard, are you trying to use two different extensions to add extra fields to the articles at the same time?

That will most likely NOT work. There are also some problems with DPfields. e.g. with adding extra fields to categories.

**Comment by schnuti** [comment]
Have a look at the bottom of this page.

https://github.com/Percha/fieldsattach_j3

I wanted to see the content of that extension. After installation not much works.
e.g. The in Joomla removed DS gives php errors.

Unpublish the DPFields plugin or ALL Fieldsattach plugins. there are more than one.

**Comment by laoneo** [comment]
Marking that issue as invalid because of incompatibility with fieldsattach.
